url: https://y7kim.github.io
# baseurl: /nazih-ahmed/

# Site settings
title: Nazih Ahmed
email: nazih.kanaaneh@gmai.com
description: "A Front-end Web Developer"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: google-plus
    url: https://plus.google.com/u/1/+maxpcs/posts
  - title: github
    url: http://github.com/max1011

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
